// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqtpnYAulhjdzRgivbFGI_erYzFvtP74M',
    appId: '1:590341871612:web:e48912233364df66054479',
    messagingSenderId: '590341871612',
    projectId: 'hotel-app-login-based-role',
    authDomain: 'hotel-app-login-based-role.firebaseapp.com',
    storageBucket: 'hotel-app-login-based-role.firebasestorage.app',
    measurementId: 'G-VDZJ7ZK01V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALUJZlPw1EIphSnWPo7PI3J4fEa73EHRU',
    appId: '1:590341871612:android:fd476e0a06bd5b92054479',
    messagingSenderId: '590341871612',
    projectId: 'hotel-app-login-based-role',
    storageBucket: 'hotel-app-login-based-role.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDL7L4uTkVU6oxaKza66ClZ-nsTgGYrqs',
    appId: '1:590341871612:ios:17ce4e3969a15b31054479',
    messagingSenderId: '590341871612',
    projectId: 'hotel-app-login-based-role',
    storageBucket: 'hotel-app-login-based-role.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDL7L4uTkVU6oxaKza66ClZ-nsTgGYrqs',
    appId: '1:590341871612:ios:17ce4e3969a15b31054479',
    messagingSenderId: '590341871612',
    projectId: 'hotel-app-login-based-role',
    storageBucket: 'hotel-app-login-based-role.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqtpnYAulhjdzRgivbFGI_erYzFvtP74M',
    appId: '1:590341871612:web:7e91269fb510d571054479',
    messagingSenderId: '590341871612',
    projectId: 'hotel-app-login-based-role',
    authDomain: 'hotel-app-login-based-role.firebaseapp.com',
    storageBucket: 'hotel-app-login-based-role.firebasestorage.app',
    measurementId: 'G-V7WK5EMZ3Q',
  );
}
